MvcSmallScreen/MvcSmallScreen/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcSmallScreen.Models
{
    public partial class ShoppingCart
    {
        PCStoreEntities storeDB = new PCStoreEntities();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart(); cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        // Вспомогательный метод для упрощения корзины
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public void AddToCart(Goods goods)
        {
            // Get the matching cart and album instances
            var cartItem = storeDB.Carts.SingleOrDefault( c => c.CartId == ShoppingCartId 
                && c.GoodsId == goods.GoodsId);
 
            if (cartItem == null)
            {
                // Создать новый товар в корзине, если нет продуктов существует 
                cartItem = new Cart
                {
                    GoodsId = goods.GoodsId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                }; 
                storeDB.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity 
                cartItem.Count++;
            }
            // Save changes 
            storeDB.SaveChanges();
        }
        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = storeDB.Carts.Single(cart => cart.CartId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--; itemCount = cartItem.Count;
                }
                else
                {
                    storeDB.Carts.Remove(cartItem);
                }
                // Save changes 
                storeDB.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = storeDB.Carts.Where(cart => cart.CartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                storeDB.Carts.Remove(cartItem);
            }
            // Save changes 
            storeDB.SaveChanges();
        }
        public List<Cart> GetCartItems()
        {
            return storeDB.Carts.Where(cart => cart.CartId == ShoppingCartId).ToList();
        }
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in storeDB.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get 
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total
            decimal? total = (from cartItems in storeDB.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count * cartItems.Goods.Price).Sum();

            return total ?? decimal.Zero;
        }
        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    GoodsId = item.GoodsId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Goods.Price,
                    Quantity = item.Count
                };
                // Установить порядок в корзине 
                orderTotal += (item.Count * item.Goods.Price); 
                storeDB.OrderDetails.Add(orderDetail);

            }
            order.Total = orderTotal;

            // Save the order 
            storeDB.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order.OrderId;
        }
        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie 
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = storeDB.Carts.Where(c => c.CartId == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            } storeDB.SaveChanges();
        }
    }
}

MvcSmallScreen/MvcSmallScreen/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using MvcSmallScreen.Models;

namespace MvcSmallScreen.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

MvcSmallScreen/MvcSmallScreen/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using MvcSmallScreen.Models;
using MvcSmallScreen.ViewModels;

namespace MvcSmallScreen.Controllers
{
    public class ShoppingCartController : Controller
    {
        PCStoreEntities storeDB = new PCStoreEntities();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/1
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedGoods = storeDB.Goods
                .Single(goods => goods.GoodsId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext); cart.AddToCart(addedGoods);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/1
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string goodName = storeDB.Carts
                .Single(item => item.RecordId == id).Goods.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(goodName) + " был удален из корзины.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
	}
}

MvcSmallScreen/MvcSmallScreen/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Корзина (" + ViewData["CartCount"] + ")", "Index", "ShoppingCart", new { id = "cart-status" })

MvcSmallScreen/MvcSmallScreen/Views/ShoppingCart/Index.cshtml
@model MvcSmallScreen.ViewModels.ShoppingCartViewModel
                  
@{
    ViewBag.Title = "Корзина"; 
}

<script src="/Scripts/jquery-1.4.4.min.js"
type="text/javascript"></script>
<script type="text/javascript">
 $(function () {
     // Document.ready -> link up remove event handler 
     $(".RemoveLink").click(function () {
     // Get the id from the link
     var recordToDelete = $(this).attr("data-id");
     if (recordToDelete != '') {
         // Perform the ajax post 
         $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
         function (data) {
             // Successful requests get here
             // Update the page elements
             if (data.ItemCount == 0)
             {
                 $('#row-' + data.DeleteId).fadeOut('slow');
             }
             else
                { $('#item-count-' + data.DeleteId).text(data.ItemCount); }

             $('#cart-total').text(data.CartTotal);
             $('#update-message').text(data.Message);
             $('#cart-status').text('Cart (' + data.CartCount + ')');
         });
     }
 });
    });
</script>
<h3>
    <em>Ваша корзина:</em> 
</h3>
<p class="button"> @Html.ActionLink("Оформить заказ >>", "AddressAndPayment", "Checkout") </p>
<div id="update-message">
</div>
<table>
    <tr>
        <th> Наименование товара </th>
        <th> Цена (каждой) </th>
        <th> Количество </th>
        <th></th>
    </tr> @foreach (var item in Model.CartItems) {
    <tr id="row-@item.RecordId">
        <td> @Html.ActionLink(item.Goods.Title, "Details", "Store", new { id = item.GoodsId }, null) </td>
        <td> @item.Goods.Price </td>
        <td id="item-count-@item.RecordId"> @item.Count </td>
        <td align="right">
            <a href="#" class="RemoveLink" data-id="@item.RecordId"> Удалить из корзины</a>
        </td>
    </tr> }
    <tr >
        <td> <b>Итого</b> </td>
        <td id="cart-total"><b> @Model.CartTotal </b></td>
        <td></td>
        <td></td>
    </tr>
</table>